name: iOS Build

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install npm dependencies
        run: npm install

      - name: Sync Capacitor iOS project
        run: npx cap sync ios

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios/App
          pod install

      - name: Build iOS App (Debug - No Code Signing)
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Upload built .app as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-app-build
          path: |
            ios/App/build/Debug-iphonesimulator/*.app
